CREATE TABLE INVOICES (
    ID INT GENERATED ALWAYS AS IDENTITY, 
    TOTAL_AMOUNT DECIMAL NOT NULL,
    GENERATED_AT TIMESTAMP,
    PAYED_AT TIMESTAMP,
    MEDICAL_HISTORY_ID INT, 

    PRIMARY KEY (ID)
);

CREATE TABLE INVOICE_ITEMS(
    ID INT GENERATED ALWAYS AS IDENTITY, 
    UNIT_PRICE DECIMAL NOT NULL, 
    QUANTITY INT NOT NULL,
    TOTAL_PRICE DECIMAL NOT NULL,
    INVOICE_ID INT NOT NULL,
    TREATMENT_ID INT NOT NULL,

    PRIMARY KEY (ID)
);

CREATE TABLE PATIENTS (
ID INT GENERATED ALWAYS AS IDENTITY,
NAME VARCHAR(255) NOT NULL,
DATE_OF_BIRTH DATE NOT NULL,

PRIMARY KEY(ID)
);

CREATE TABLE MEDICAL_HISTORIES (
    ID INT GENERATED ALWAYS AS IDENTITY,
    ADMITTED_AT TIMESTAMP,
    PATIENT_ID INT NOT NULL,
    STATUS VARCHAR(120),

    PRIMARY KEY(ID)
);

CREATE TABLE TREATMENTS (
    ID INT GENERATED ALWAYS AS IDENTITY, 
    TYPE VARCHAR(255) NOT NULL,
    NAME VARCHAR(255) NOT NULL, 

    PRIMARY KEY(ID)
);

ALTER TABLE MEDICAL_HISTORIES ADD CONSTRAINT FK_PATIENTS
        FOREIGN KEY(PATIENT_ID)
        REFERENCES PATIENTS(ID) 
        ON DELETE CASCADE;

CREATE INDEX ON MEDICAL_HISTORIES(PATIENT_ID); 

ALTER TABLE INVOICES ADD CONSTRAINT FK_MEDICAL_HISTORY
        FOREIGN KEY(MEDICAL_HISTORY_ID)
        REFERENCES MEDICAL_HISTORIES(ID)
        ON DELETE CASCADE;

CREATE INDEX ON INVOICES(MEDICAL_HISTORY_ID); 


ALTER TABLE INVOICE_ITEMS ADD CONSTRAINT FK_INVOICE
        FOREIGN KEY(INVOICE_ID) 
        REFERENCES INVOICES(ID)
        ON DELETE CASCADE;

CREATE INDEX ON INVOICE_ITEMS(INVOICE_ID); 

ALTER TABLE INVOICE_ITEMS ADD CONSTRAINT FK_TREATMENTS
        FOREIGN KEY(TREATMENT_ID) 
        REFERENCES TREATMENTS(ID)
        ON DELETE CASCADE;

CREATE INDEX ON INVOICE_ITEMS(TREATMENT_ID); 

 CREATE TABLE MEDICAL_HISTORIES_TREATMENTS (
    ID INT GENERATED ALWAYS AS IDENTITY, 
    MEDICAL_HISTORIES_ID INT,
    TREATMENT_ID INT,

    PRIMARY KEY(ID),

    CONSTRAINT FK_MEDICAL_HISTORY_ID 
    FOREIGN KEY (MEDICAL_HISTORIES_ID)
    REFERENCES MEDICAL_HISTORIES(ID),

    CONSTRAINT FK_TREATMENTS_ID 
    FOREIGN KEY (TREATMENT_ID)
    REFERENCES TREATMENTS(ID)
);

CREATE INDEX ON MEDICAL_HISTORIES_TREATMENTS(MEDICAL_HISTORIES_ID); 
CREATE INDEX ON MEDICAL_HISTORIES_TREATMENTS(TREATMENT_ID);
